name: wallet_app
description: A Flutter project to track your income and expenses.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  animated_text_kit: 4.2.2
  buttons_tabbar: 1.3.6
  dialogs: 0.0.7
  flutter:
    sdk: flutter
  flutter_email_sender: 5.2.0
  flutter_slidable: 2.0.0
  flutter_speed_dial: 6.2.0
  hive: 2.2.3
  hive_flutter: 1.1.0
  intl: 0.18.0
  provider: 
  share_plus: 6.3.1
  syncfusion_flutter_charts: 20.4.44

dev_dependencies:
  build_runner: 2.3.3
  flutter_launcher_icons: ^0.12.0
  flutter_lints: 2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: 2.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/ic_launcher.png"

flutter:

  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/ic_launcher.png
    - assets/images/Document Icon.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
